// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuomVDqWWqMDm0h3GGZI5vZuWIbSvSn90',
    appId: '1:594527888713:web:4abaaf662abffeb9086698',
    messagingSenderId: '594527888713',
    projectId: 'inventory-app-f8ff6',
    authDomain: 'inventory-app-f8ff6.firebaseapp.com',
    storageBucket: 'inventory-app-f8ff6.firebasestorage.app',
    measurementId: 'G-WS5HEG6QKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuomVDqWWqMDm0h3GGZI5vZuWIbSvSn90',
    appId: '1:594527888713:android:4abaaf662abffeb9086698',
    messagingSenderId: '594527888713',
    projectId: 'inventory-app-f8ff6',
    storageBucket: 'inventory-app-f8ff6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuomVDqWWqMDm0h3GGZI5vZuWIbSvSn90',
    appId: '1:594527888713:ios:4abaaf662abffeb9086698',
    messagingSenderId: '594527888713',
    projectId: 'inventory-app-f8ff6',
    storageBucket: 'inventory-app-f8ff6.firebasestorage.app',
    iosBundleId: 'com.warungin.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuomVDqWWqMDm0h3GGZI5vZuWIbSvSn90',
    appId: '1:594527888713:ios:4abaaf662abffeb9086698',
    messagingSenderId: '594527888713',
    projectId: 'inventory-app-f8ff6',
    storageBucket: 'inventory-app-f8ff6.firebasestorage.app',
    iosBundleId: 'com.warungin.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuomVDqWWqMDm0h3GGZI5vZuWIbSvSn90',
    appId: '1:594527888713:web:4abaaf662abffeb9086698',
    messagingSenderId: '594527888713',
    projectId: 'inventory-app-f8ff6',
    authDomain: 'inventory-app-f8ff6.firebaseapp.com',
    storageBucket: 'inventory-app-f8ff6.firebasestorage.app',
    measurementId: 'G-WS5HEG6QKV',
  );
}
